name: Teste Frontend Robot Framework

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      # 1️⃣ Clonar o repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣ Instalar dependências do sistema (incluindo Chrome)
      - name: Install System Dependencies
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y wget unzip curl || true

          # Instalar Google Chrome
          wget -q -O google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
          google-chrome --version

      # 4️⃣ Instalar dependências do Python
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework selenium robotframework-seleniumlibrary

      # 5️⃣ Rodar testes Robot Framework
      - name: Run Robot Tests
        run: |
          robot -d results tests/

      # 6️⃣ Upload de relatórios (opcional)
      - name: Upload Robot Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: results/
